Traceback (most recent call last):
  File "/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
m = Prophet()
m.fit(train_df);
------------------

----- stderr -----
16:17:24 - cmdstanpy - INFO - Chain [1] start processing
----- stderr -----
16:17:24 - cmdstanpy - INFO - Chain [1] done processing
----- stderr -----
16:17:24 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 9 Unknown error: -9
----- stderr -----
Optimization terminated abnormally. Falling back to Newton.
----- stderr -----
16:17:24 - cmdstanpy - INFO - Chain [1] start processing
----- stderr -----
16:17:24 - cmdstanpy - INFO - Chain [1] done processing
----- stderr -----
16:17:24 - cmdstanpy - ERROR - Chain [1] error: terminated by signal 9 Unknown error: -9
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
File [0;32m~/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/prophet/models.py:121[0m, in [0;36mCmdStanPyBackend.fit[0;34m(self, stan_init, stan_data, **kwargs)[0m
[1;32m    120[0m [38;5;28;01mtry[39;00m:
[0;32m--> 121[0m     [38;5;28mself[39m[38;5;241m.[39mstan_fit [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmodel[49m[38;5;241;43m.[39;49m[43moptimize[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[1;32m    122[0m [38;5;28;01mexcept[39;00m [38;5;167;01mRuntimeError[39;00m [38;5;28;01mas[39;00m e:
[1;32m    123[0m     [38;5;66;03m# Fall back on Newton[39;00m

File [0;32m~/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/cmdstanpy/model.py:659[0m, in [0;36mCmdStanModel.optimize[0;34m(self, data, seed, inits, output_dir, sig_figs, save_profile, algorithm, init_alpha, tol_obj, tol_rel_obj, tol_grad, tol_rel_grad, tol_param, history_size, iter, save_iterations, require_converged, show_console, refresh, time_fmt, timeout, jacobian)[0m
[1;32m    658[0m     [38;5;28;01melse[39;00m:
[0;32m--> 659[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(msg)
[1;32m    660[0m mle [38;5;241m=[39m CmdStanMLE(runset)

[0;31mRuntimeError[0m: Error during optimization! Command '/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/prophet/stan_model/prophet_model.bin random seed=13232 data file=/var/folders/n0/1qj4_6k97ms4rnr_bsfq6j40018_cq/T/tmpplzcp64k/lcn3cev2.json init=/var/folders/n0/1qj4_6k97ms4rnr_bsfq6j40018_cq/T/tmpplzcp64k/i9z6n41n.json output file=/var/folders/n0/1qj4_6k97ms4rnr_bsfq6j40018_cq/T/tmpplzcp64k/prophet_model6x5_dgov/prophet_model-20250106161724.csv method=optimize algorithm=lbfgs iter=10000' failed: 

During handling of the above exception, another exception occurred:

[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[11], line 2[0m
[1;32m      1[0m m [38;5;241m=[39m Prophet()
[0;32m----> 2[0m [43mm[49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43mtrain_df[49m[43m)[49m;

File [0;32m~/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/prophet/forecaster.py:1232[0m, in [0;36mProphet.fit[0;34m(self, df, **kwargs)[0m
[1;32m   1230[0m     [38;5;28mself[39m[38;5;241m.[39mparams [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mstan_backend[38;5;241m.[39msampling(stan_init, dat, [38;5;28mself[39m[38;5;241m.[39mmcmc_samples, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   1231[0m [38;5;28;01melse[39;00m:
[0;32m-> 1232[0m     [38;5;28mself[39m[38;5;241m.[39mparams [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mstan_backend[49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43mstan_init[49m[43m,[49m[43m [49m[43mdat[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   1234[0m [38;5;28mself[39m[38;5;241m.[39mstan_fit [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mstan_backend[38;5;241m.[39mstan_fit
[1;32m   1235[0m [38;5;66;03m# If no changepoints were requested, replace delta with 0s[39;00m

File [0;32m~/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/prophet/models.py:128[0m, in [0;36mCmdStanPyBackend.fit[0;34m(self, stan_init, stan_data, **kwargs)[0m
[1;32m    126[0m     logger[38;5;241m.[39mwarning([38;5;124m'[39m[38;5;124mOptimization terminated abnormally. Falling back to Newton.[39m[38;5;124m'[39m)
[1;32m    127[0m     args[[38;5;124m'[39m[38;5;124malgorithm[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;124m'[39m[38;5;124mNewton[39m[38;5;124m'[39m
[0;32m--> 128[0m     [38;5;28mself[39m[38;5;241m.[39mstan_fit [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmodel[49m[38;5;241;43m.[39;49m[43moptimize[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[1;32m    129[0m params [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mstan_to_dict_numpy(
[1;32m    130[0m     [38;5;28mself[39m[38;5;241m.[39mstan_fit[38;5;241m.[39mcolumn_names, [38;5;28mself[39m[38;5;241m.[39mstan_fit[38;5;241m.[39moptimized_params_np)
[1;32m    131[0m [38;5;28;01mfor[39;00m par [38;5;129;01min[39;00m params:

File [0;32m~/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/cmdstanpy/model.py:659[0m, in [0;36mCmdStanModel.optimize[0;34m(self, data, seed, inits, output_dir, sig_figs, save_profile, algorithm, init_alpha, tol_obj, tol_rel_obj, tol_grad, tol_rel_grad, tol_param, history_size, iter, save_iterations, require_converged, show_console, refresh, time_fmt, timeout, jacobian)[0m
[1;32m    657[0m         get_logger()[38;5;241m.[39mwarning(msg)
[1;32m    658[0m     [38;5;28;01melse[39;00m:
[0;32m--> 659[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(msg)
[1;32m    660[0m mle [38;5;241m=[39m CmdStanMLE(runset)
[1;32m    661[0m [38;5;28;01mreturn[39;00m mle

[0;31mRuntimeError[0m: Error during optimization! Command '/Users/kashnitsky/Library/Caches/pypoetry/virtualenvs/mlcourse-ai-L-dGjTF0-py3.12/lib/python3.12/site-packages/prophet/stan_model/prophet_model.bin random seed=94163 data file=/var/folders/n0/1qj4_6k97ms4rnr_bsfq6j40018_cq/T/tmpplzcp64k/1vdfnbpd.json init=/var/folders/n0/1qj4_6k97ms4rnr_bsfq6j40018_cq/T/tmpplzcp64k/37dzl9tg.json output file=/var/folders/n0/1qj4_6k97ms4rnr_bsfq6j40018_cq/T/tmpplzcp64k/prophet_modelnv76xx_r/prophet_model-20250106161724.csv method=optimize algorithm=newton iter=10000' failed: 

